Web_Farmacia/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Farmacia.Clases;
using Web_Farmacia.Models;

namespace Web_Farmacia.Controllers
{
    public class CargoController : Controller
    {
        Cargo v_car = new Cargo();
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Consultar_Cargo()
        {
            List<Cargo> car;
            Metodo_Cargo mc = new Metodo_Cargo();

            Info datos = new Info();

            //List<Object> todo = new List<Object>();

            car = mc.listar();

            ViewBag.eliminar = TempData["Eliminar"];

            datos.Car = car;

            return View(datos);
        }

        public ActionResult eliminar(int id)
        {
            Metodo_Cargo mc = new Metodo_Cargo();
            if (mc.eliminar(id))
            {
                TempData["Eliminar"] = "Se eliminó Correctamente el Registro";
            }
            else
            {
                TempData["Eliminar"] = "No se eliminó Correctamente el Registro";
            }

            return RedirectToAction("Consultar_Cargo");
        }

        public ActionResult Modificar_Cargo(int? id)
        {

            Metodo_Cargo mc = new Metodo_Cargo();

            if (id != null)
            {
                v_car = mc.obtener(id);

                Info datos = new Info();
                datos.Obj_car = v_car;

                return View(datos);
            }
            else
            {
                return RedirectToAction("Consultar_Cargo");
            }



        }
        [HttpPost]
        public ActionResult Modificar_Cargo(int? id, string nombre, string detalle)
        {
            Metodo_Cargo mc = new Metodo_Cargo();
            Cargo car = new Cargo();
            string message;
            SortedList<string, string> error = new SortedList<string, string>();

            if (id != null)
            {
                if (String.IsNullOrEmpty(nombre))
                {
                    error.Add("sp_nombre", "Ingrese el nombre del Cliente");
                }
                if (String.IsNullOrEmpty(detalle))
                {
                    error.Add("sp_detalle", "Ingrese la descripción del cargo");
                }

                //if(!String.IsNullOrEmpty(nombre) & categoria != null & precio != null & stock != null & !String.IsNullOrEmpty(codigo) & !String.IsNullOrEmpty(descripcion))
                //{
                if (error.Count == 0)
                {
                    car.Id_cargo = id;
                    car.Nombre = nombre == null ? "" : nombre;
                    car.Detalle = detalle == null ? "" : detalle;
                    
                    if (mc.actualizar(car))
                    {
                        message = "Se actualizaron los datos correctamente";
                    }
                    else
                    {
                        message = "No se logró actualizar lo datos";
                    }

                    return Json(new { message = message, success = true });
                }
                else
                {
                    message = "Ingrese los datos necesarios";
                    return Json(new { message = message, success = false, datos = error });
                }


                //--------------------------------------------------------------

            }

            return RedirectToAction("Consultar_Cargo");
        }

        public ActionResult Registrar_Cargo()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Registrar_Cargo(string nombre, string detalle)
        {
            Cargo car = new Cargo();
            Metodo_Cargo mc = new Metodo_Cargo();

            string message;
            SortedList<string, string> error = new SortedList<string, string>();

            if (String.IsNullOrEmpty(nombre))
            {
                error.Add("sp_nombre", "Ingrese el nombre del Cargo");
            }
            if (String.IsNullOrEmpty(detalle))
            {
                error.Add("sp_detalle", "Ingrese la descripción del cargo");
            }

            if (error.Count == 0)
            {
                car.Nombre = nombre == null ? "" : nombre;
                car.Detalle = detalle == null ? "" : detalle;

                if (mc.guardar(car))
                {
                    message = "Se guardaron los datos correctamente";
                }
                else
                {
                    message = "No se Guardaron lo datos";
                }

                return Json(new { message = message, success = true });
            }
            else
            {
                message = "Ingrese los datos necesarios";
                return Json(new { message = message, success = false, datos = error });
            }


        }
    }
}

Web_Farmacia/Views/Cargo/Consultar_Cargo.cshtml
@{
    ViewBag.Title = "Consultar_Cargo";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Lista de Cargos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Lista de Cargos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Cargos</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @model Web_Farmacia.Controllers.Info

            <!-- Table row -->

            @if (ViewBag.eliminar != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.eliminar
                </div>
            }

            <div class="d-flex mb-4">
                <a href="@Url.Action("Registrar_Cargo", "Cargo")" class="btn btn-secondary ml-auto"><i class="fa fa-plus"></i> Agregar</a>
            </div>

            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Detalle</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var cargo in Model.Car)
                                {
                                    <tr>
                                        <td>@cargo.Nombre</td>
                                        <td>@cargo.Detalle</td>
                                        <td class="text-center">
                                            <a href="/Cargo/Modificar_Cargo?id=@cargo.Id_cargo" class="btn btn-primary" id="actualizar"><i class="fa fa-edit"></i></a>
                                            <button onclick="eliminar('@cargo.Id_cargo')" class="btn btn-danger" id="Eliminar"><i class="fa fa-trash"></i></button>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content">Desea eliminar el Cargo?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"> Eliminar</button><button class="btn btn-secondary" id="mod-can">Cancelar</button>
            </div>
        </div>

    </div>


</div>

<script>

    var f_id;

    document.addEventListener("DOMContentLoaded", function (e) {



        document.getElementById("mod-acept").addEventListener("click", function () {
            location.replace("/Cargo/eliminar?id=" + f_id);
            $("#mod").modal("hide");
        })
        document.getElementById("mod-can").addEventListener("click", function () {
            $("#mod").modal("hide");
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })

    function eliminar(id) {
        $("#mod").modal({ backdrop: true });
        f_id = id;
    }


</script>

Web_Farmacia/Views/Cargo/Modificar_Cargo.cshtml
@{
    ViewBag.Title = "Modificar_Cargo";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Modificar Cargo</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Modificar Cargo</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Modificar</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @model Web_Farmacia.Controllers.Info



            <form method="post" enctype="multipart/form-data" id="modificar">
                <div class="d-flex">
                    <a href="@Url.Action("Consultar_Cargo", "Cargo")" class="btn btn-secondary ml-auto"><i class="fa fa-caret-left"></i> Regresar</a>
                </div>

                <div class="form-row">

                    <input class="form-control" type="hidden" name="id" id="id" value="@Model.Obj_car.Id_cargo">

                    <div class="form-group col-sm-6">
                        <label for="nombre">Nombre</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre" value="@Model.Obj_car.Nombre">
                        <span class="badge badge-warning sp" id="sp_nombre"></span>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="detalle">Detalle</label>
                        <input class="form-control" type="text" name="detalle" id="detalle" placeholder="Ingrese el Detalle" value="@Model.Obj_car.Detalle">
                        <span class="badge badge-warning sp" id="sp_detalle"></span>
                    </div>
                </div>


                <div class="form-group col-auto">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>



        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->

<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"><i class="fa fa-caret-left"></i> Regresar</button>
            </div>
        </div>

    </div>


</div>

<script>
    document.addEventListener("DOMContentLoaded", function (e) {

        document.getElementById("modificar").addEventListener("submit", function (e) {

            var url = "@Url.Action("Modificar_Cargo", "Cargo")"/*"/Producto/Registrar_Producto"*/;

            //var form = document.getElementById("registrar");
            var id = document.getElementById("id").value;
            var nombre = document.getElementById("nombre").value;
            var detalle = document.getElementById("detalle").value;
            //var formdata = new FormData();

            var param = "id=" + id + "&nombre=" + nombre + "&detalle=" + detalle;
            var ajax = new XMLHttpRequest();

            ajax.onreadystatechange = function () {
                if (ajax.readyState == 4) {

                    //console.log(JSON.parse(ajax.responseText));

                    var response = JSON.parse(ajax.responseText);
                    if (response.success) {
                        console.log(response.message);

                        document.getElementById("content").innerHTML = response.message;
                        $("#mod").modal({ backdrop: true });
                        limpiar_spam();
                    } else {
                        console.log(response);
                        limpiar_spam();
                        for (var prop in response.datos) {
                            //console.log("propiedad " + prop + " valor " + response.datos[prop]);
                            document.getElementById(prop).innerHTML = response.datos[prop]
                        }
                    }
                }
            }

            ajax.open("POST", url, true);
            ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            //console.log(formdata.toString);
            ajax.send(param);

            e.preventDefault();
        })

        document.getElementById("mod-acept").addEventListener("click", function () {
            $("#mod").modal("hide");

            location.replace("@Url.Action("Consultar_Cargo", "Cargo")");
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })


</script>

Web_Farmacia/Views/Cargo/Registrar_Cargo.cshtml
@{
    ViewBag.Title = "Registrar_Cargo";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar Cargo</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Registrar Cargo</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Registrar</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @if (ViewBag.message != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.message
                </div>
            }

            <form name="registrar" method="post" enctype="multipart/form-data" id="registrar">

                <div class="d-flex">
                    <a href="@Url.Action("Consultar_Cargo", "Cargo")" class="btn btn-secondary ml-auto"><i class="fa fa-caret-left"></i> Lista de Categorias</a>
                </div>

                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="nombre">Nombre</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre">
                        <span class="badge badge-warning sp" id="sp_nombre"></span>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="detalle">Detalle</label>
                        <input class="form-control" type="text" name="detalle" id="detalle" placeholder="Ingrese el Detalle">
                        <span class="badge badge-warning sp" id="sp_detalle"></span>
                    </div>
                </div>

                <div class="form-group col-auto">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>

            </form>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"> Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (e) {

        document.getElementById("registrar").addEventListener("submit", function (e) {

            var url = "@Url.Action("Registrar_Cargo", "Cargo")"/*"/Producto/Registrar_Producto"*/;

            //var form = document.getElementById("registrar");
            var nombre = document.getElementById("nombre").value;
            var detalle = document.getElementById("detalle").value;

            var formdata = new FormData();

            formdata.append("nombre", nombre);
            formdata.append("detalle", detalle);

            //var param = "nombre=" + nombre + "&descripcion=" + descripcion;
            var ajax = new XMLHttpRequest();

            ajax.onreadystatechange = function () {
                if (ajax.readyState == 4) {

                    //console.log(JSON.parse(ajax.responseText));

                    var response = JSON.parse(ajax.responseText);
                    if (response.success) {
                        console.log(response.message);

                        document.getElementById("content").innerHTML = response.message;
                        $("#mod").modal({ backdrop: true });
                        limpiar_spam();
                    } else {
                        console.log(response);
                        limpiar_spam();
                        for (var prop in response.datos) {
                            //console.log("propiedad " + prop + " valor " + response.datos[prop]);
                            document.getElementById(prop).innerHTML = response.datos[prop]
                        }
                    }
                }
            }

            ajax.open("POST", url, true);
            //ajax.setRequestHeader("Content-Type", "multipart/byteranges");
            //console.log(formdata.toString);
            ajax.send(formdata/*param*/);

            e.preventDefault();
        })

        //--------------------------------------------

        document.getElementById("mod-acept").addEventListener("click", function () {
            $("#mod").modal("hide");

            document.getElementById("nombre").value = "";
            document.getElementById("detalle").value = "";

        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })




</script>