Web_Farmacia/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Farmacia.Clases;
using Web_Farmacia.Models;

namespace Web_Farmacia.Controllers
{
    public class VentaController : Controller
    {
        Venta v_ven = new Venta();
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Consultar_Venta()
        {
            List<Venta> ven;
            Metodo_Venta mv = new Metodo_Venta();
            List<Cliente> cli;
            Metodo_Cliente mc = new Metodo_Cliente();

            Info datos = new Info();

            //List<Object> todo = new List<Object>();

            ven = mv.listar();
            cli = mc.listar();

            ViewBag.eliminar = TempData["Eliminar"];

            datos.Ven = ven;
            datos.Cli = cli;

            return View(datos);
        }
        [HttpPost]
        public ActionResult Consultar_Venta(int? id_cliente, DateTime fecha, string serie)
        {
            List<Venta> ven;
            //List<Categoria> cat;
            Metodo_Venta mv = new Metodo_Venta();
            //Metodo_Categoria mc = new Metodo_Categoria();
            Info datos = new Info();
            //List<Object> todo = new List<Object>();

            ven = mv.listar();

            ViewBag.eliminar = TempData["Eliminar"];

            datos.Ven = ven;

            return View(datos);
        }

        public ActionResult eliminar(int id)
        {
            Metodo_Venta mv = new Metodo_Venta();
            if (mv.eliminar(id))
            {
                TempData["Eliminar"] = "Se eliminó Correctamente el Registro";
            }
            else
            {
                TempData["Eliminar"] = "No se eliminó Correctamente el Registro";
            }

            return RedirectToAction("Consultar_Venta");
        }

        public ActionResult Modificar_Venta(int? id)
        {

            Metodo_Venta mv = new Metodo_Venta();

            if (id != null)
            {
                v_ven = mv.obtener(id);

                Info datos = new Info();
                datos.Obj_ven = v_ven;

                return View(datos);
            }
            else
            {
                return RedirectToAction("Consultar_Venta");
            }



        }
        [HttpPost]
        public ActionResult Modificar_Venta(int? id, int? id_cliente, DateTime fecha, string t_comprobante, string serie_com, string nro_com, int? total, int? id_usuario, string est_entrega, string estado)
        {
            Metodo_Venta mv = new Metodo_Venta();
            Venta ven = new Venta();
            string message;
            SortedList<string, string> error = new SortedList<string, string>();

            if (id != null)
            {
                if (id_cliente == null)
                {
                    error.Add("sp_id_cliente", "Seleccione el Cliente");
                }
                if (fecha == null)
                {
                    error.Add("sp_fecha", "Ingrese la fecha del pedido");
                }
                if (String.IsNullOrEmpty(t_comprobante))
                {
                    error.Add("sp_t_comprobante", "Seleccione el tipo de comprobante");
                }
                if (String.IsNullOrEmpty(serie_com))
                {
                    error.Add("sp_serie_com", "Ingrese la serie del comprobante");
                }
                if (String.IsNullOrEmpty(nro_com))
                {
                    error.Add("sp_nro_com", "Ingrese el N° del Comprobante");
                }
                if (total == null)
                {
                    error.Add("sp_total", "Calcule el Total");
                }
                if (id_usuario == null)
                {
                    error.Add("sp_id_usuario", "Necesita un usuario");
                }
                if (String.IsNullOrEmpty(est_entrega))
                {
                    error.Add("sp_est_entrega", "Seleccione el estado de la entrega");
                }
                if (String.IsNullOrEmpty(estado))
                {
                    error.Add("sp_estado", "Seleccione el estado del pedido");
                }

                //if(!String.IsNullOrEmpty(nombre) & categoria != null & precio != null & stock != null & !String.IsNullOrEmpty(codigo) & !String.IsNullOrEmpty(descripcion))
                //{
                if (error.Count == 0)
                {
                    ven.Id_venta = id;
                    ven.Id_cliente = id_cliente == null ? 0 : id_cliente;
                    ven.Fecha = fecha == null ? DateTime.Now : fecha;
                    ven.T_comprobante = t_comprobante == null ? "" : t_comprobante;
                    ven.S_comprobante = serie_com == null ? "" : serie_com;
                    ven.N_comprobante = nro_com == null ? "" : nro_com;
                    ven.Total = total == null ? 0 : total;
                    ven.Id_usuario = id_usuario == null ? 0 : id_usuario;
                    ven.Est_entrega = est_entrega == null ? "" : est_entrega;
                    ven.Estado = estado == null ? "" : estado;

                    if (mv.actualizar(ven))
                    {
                        message = "Se actualizaron los datos correctamente";
                    }
                    else
                    {
                        message = "No se logró actualizar lo datos";
                    }

                    return Json(new { message = message, success = true });
                }
                else
                {
                    message = "Ingrese los datos necesarios";
                    return Json(new { message = message, success = false, datos = error });
                }


                //--------------------------------------------------------------

            }

            return RedirectToAction("Consultar_Venta");
        }

        public ActionResult Registrar_Venta()
        {
            List<Cliente> cli = new List<Cliente>();
            Metodo_Cliente mc = new Metodo_Cliente();
            Metodo_Producto mp = new Metodo_Producto();
            List<Producto> pro = new List<Producto>();
            Info datos = new Info();

            pro = mp.listar();
            cli = mc.listar();

            datos.Cli = cli;
            datos.Prod = pro;

            return View(datos);
        }

        [HttpPost]
        public JsonResult Registrar_Venta(int? id_cliente, DateTime? fecha, string t_comprobante, string serie_com, string nro_com, int? total_venta, int? id_usuario,
            string est_entrega, string estado, int?[] id_producto, int?[] cantidad, Double?[] precio, Double?[] art_total)
        {
            Venta ven = new Venta();
            DetalleVenta dven = new DetalleVenta();

            Metodo_Venta mv = new Metodo_Venta();
            Metodo_DetalleVenta mdv = new Metodo_DetalleVenta();

            int id_Venta;

            string message;
            SortedList<string, string> error = new SortedList<string, string>();

            if (id_cliente == null)
            {
                error.Add("sp_id_cliente", "Seleccione el Cliente");
            }
            if (fecha == null)
            {
                error.Add("sp_fecha", "Ingrese la fecha del pedido");
            }
            if (String.IsNullOrEmpty(t_comprobante))
            {
                error.Add("sp_t_comprobante", "Seleccione el tipo de comprobante");
            }
            if (String.IsNullOrEmpty(serie_com))
            {
                error.Add("sp_serie_com", "Ingrese la serie del comprobante");
            }
            if (String.IsNullOrEmpty(nro_com))
            {
                error.Add("sp_nro_com", "Ingrese el N° del Comprobante");
            }
            if (total_venta == null)
            {
                error.Add("sp_total_venta", "Calcule el Total");
            }
            if (id_usuario == null)
            {
                error.Add("sp_id_usuario", "Necesita un usuario");
            }
            if (String.IsNullOrEmpty(est_entrega))
            {
                error.Add("sp_est_entrega", "Seleccione el estado de la entrega");
            }
            if (String.IsNullOrEmpty(estado))
            {
                error.Add("sp_estado", "Seleccione el estado del pedido");
            }
            //------------------------------------------------------------------------
            if (id_producto == null | cantidad == null | precio == null | art_total == null)
            {
                error.Add("sp_detalle_productos", "Agregue los productos de compra correctamente");
            }

            if (error.Count == 0)
            {
                ven.Id_cliente = id_cliente == null ? 0 : id_cliente;
                ven.Fecha = fecha == null ? DateTime.Now : fecha;
                ven.T_comprobante = t_comprobante == null ? "" : t_comprobante;
                ven.S_comprobante = serie_com == null ? "" : serie_com;
                ven.N_comprobante = nro_com == null ? "" : nro_com;
                ven.Total = total_venta == null ? 0 : total_venta;
                ven.Id_usuario = id_usuario == null ? 0 : id_usuario;
                ven.Est_entrega = est_entrega == null ? "" : est_entrega;
                ven.Estado = estado == null ? "" : estado;

                id_Venta = mv.guardar(ven);

                if (id_Venta>0)
                {

                    message = "Se guardaron los datos de venta";

                    for(int i=0; id_producto.Length> i; i++)
                    {
                        dven.Id_producto = id_producto[i];
                        dven.Id_venta = id_Venta;
                        dven.Cantidad = cantidad[i];
                        dven.Precio = precio[i];
                        dven.Total = art_total[i];

                        if (mdv.guardar(dven))
                        {

Web_Farmacia/Views/Venta/Consultar_Venta.cshtml
@{
    ViewBag.Title = "Consultar_Venta";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Lista de Pedidos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Listar Pedidos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Pedidos</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">


            @model Web_Farmacia.Controllers.Info

            <div class="d-flex mb-4">
                <a href="@Url.Action("Registrar_Venta", "Venta")" class="btn btn-secondary ml-auto"><i class="fa fa-plus"></i> Agregar</a>
            </div>


            <form action="/Venta/Consultar_Venta" method="post" class="">

                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="id_cliente">Cliente</label>
                        <select class="form-control" name="id_cliente" id="id_cliente">

                            <option value="" selected="selected">[Todos]</option>

                            @foreach (var cliente in Model.Cli)
                            {
                                <option value="@cliente.Id_cliente">@cliente.Nombre</option>
                            }
                        </select>
                        @*<input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre">*@
                    </div>
                    <div class="form-group col-sm-4">
                        <label for="fecha">Fecha</label>
                        <input type="date" name="fecha" id="fecha" class="form-control" />
                    </div>
                    <div class="col-sm-2 align-self-center align-self-end text-center">
                        <button type="submit" class="btn btn-primary pr-4 pl-4">Buscar</button>
                    </div>

                </div>
            </form>
            <!-- Table row -->

            @if (ViewBag.eliminar != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.eliminar
                </div>
            }

            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Fecha</th>
                                <th>Comprobante</th>
                                <th>Serie</th>
                                <th>Número</th>
                                <th>Total</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var venta in Model.Ven)
                                {
                                    <tr>
                                        <td>@venta.Cliente</td>
                                        <td>@venta.Fecha</td>
                                        <td>@venta.T_comprobante</td>
                                        <td>@venta.S_comprobante</td>
                                        <td>@venta.N_comprobante</td>
                                        <td>@venta.Total</td>
                                        <td class="text-center">
                                            <a href="/Venta/Modificar_Venta?id=@venta.Id_venta" class="btn btn-primary" id="actualizar"><i class="fa fa-edit"></i></a>
                                            <button onclick="eliminar('@venta.Id_venta')" class="btn btn-danger" id="Eliminar"><i class="fa fa-trash"></i></button>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>




        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content">Desea eliminar el Producto?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"> Eliminar</button><button class="btn btn-secondary" id="mod-can">Cancelar</button>
            </div>
        </div>

    </div>


</div>

<script>

    var f_id;

    document.addEventListener("DOMContentLoaded", function (e) {



        document.getElementById("mod-acept").addEventListener("click", function () {
            location.replace("/Producto/eliminar?id=" + f_id);
            $("#mod").modal("hide");
        })
        document.getElementById("mod-can").addEventListener("click", function () {
            $("#mod").modal("hide");
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })

    function eliminar(id) {
        $("#mod").modal({ backdrop: true });
        f_id = id;
    }


</script>

Web_Farmacia/Views/Venta/Modificar_Venta.cshtml
@{
    ViewBag.Title = "Modificar_Venta";
    Layout = "~/Views/Main.cshtml";
}

<h2>Modificar_Venta</h2>