Web_Farmacia/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Farmacia.Clases;
using Web_Farmacia.Models;

namespace Web_Farmacia.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Consultar_Categoria()
        {
            List<Categoria> lista;
            Metodo_Categoria mc = new Metodo_Categoria();

            lista = mc.listar();

            ViewBag.eliminar = TempData["Eliminar"];
            ViewBag.modificar = TempData["Modificar"];
        
            return View(lista);
        }
       
        public ActionResult eliminar(int id)
        {
            Metodo_Categoria mc = new Metodo_Categoria();
            if (mc.eliminar(id))
            {
                TempData.Add("Eliminar", "Se eliminó Correctamente el Registro");
            }
            else
            {
                TempData.Add("Eliminar", "No se eliminó Correctamente el Registro");
            }

            return RedirectToAction("Consultar_Categoria");
        }

        public ActionResult Modificar_Categoria(int ? id)
        {
            Categoria cat = new Categoria();
            Metodo_Categoria mc = new Metodo_Categoria();

            if (id != null)
            {
                cat = mc.obtener(id);
                return View(cat);
            }
            else
            {
                return RedirectToAction("Consultar_Categoria");
            }
            
        }
        [HttpPost]
        public ActionResult Modificar_Categoria(int ? id, string nombre, string descripcion)
        {
            Metodo_Categoria mc = new Metodo_Categoria();
            Categoria cat = new Categoria();
            string message;

            SortedList<string, string> datos = new SortedList<string, string>();

            if (id != null)
            {
                if (String.IsNullOrEmpty(nombre))
                {
                    datos.Add("sp_nombre", "Ingrese el nombre de la categoría");
                }
                if (String.IsNullOrEmpty(descripcion))
                {
                    datos.Add("sp_descripcion", "Ingrese la descripción de la Categoría");
                }

                if (datos.Count == 0)
                {
                    cat.Id_categoria = id;
                    cat.Nombre = nombre;
                    cat.Descripcion = descripcion;
            
                    if (mc.actualizar(cat))
                    {
                        message = "Se actualizaron los datos correctamente";
                    }
                    else
                    {
                        message = "No se pudo actualizar los datos";
                    }

                    return Json(new { message = message, success = true });
                }
                else
                {
                    return Json(new { message = "Necesita completar los datos necesarios", success = false, datos });
                }
            }

            return RedirectToAction("Consultar_Categoria");
        }

        public ActionResult Registrar_Categoria()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrar_Categoria(string nombre, string descripcion)
        {
            Categoria cat = new Categoria();
            Metodo_Categoria mc = new Metodo_Categoria();
            string message;

            SortedList<string, string> error = new SortedList<string, string>();

            if (String.IsNullOrEmpty(nombre))
            {
                error.Add("sp_nombre", "Ingrese el Nombre de la Categoría");
            }
            if (String.IsNullOrEmpty(descripcion))
            {
                error.Add("sp_descripcion", "Ingrese la Descripción");
            }

            if (error.Count == 0)
            {
                cat.Nombre = nombre;
                cat.Descripcion = descripcion;

                if (mc.guardar(cat))
                {
                    message = "Se guardaron los datos correctamente";
                }
                else
                {
                    message = "No se Guardaron los datos";
                }

                return Json(new {message = message, success = true });
            }
            else
            {
                return Json(new { message = "Necesita completar los campos necesarios", success = false, datos = error });
            }

            
        }
    }
}

Web_Farmacia/Views/Categoria/Consultar_Categoria.cshtml
@{
    ViewBag.Title = "Consultar_Categoria";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Lista de Categorias</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Lista de Categorias</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Categorias </h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @model List<Web_Farmacia.Clases.Categoria>

            <!-- Table row -->

            @if (ViewBag.eliminar != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.eliminar
                </div>
            }

            @if (ViewBag.modificar != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.modificar
                </div>
            }

            <div class="d-flex mb-4">
                <a href="@Url.Action("Registrar_Categoria", "Categoria")" class="btn btn-secondary ml-auto" @*id="return"*@><i class="fa fa-plus"></i> Agregar</a>
            </div>

            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var categoria in Model)
                                {
                                    <tr>
                                        <td>@categoria.Nombre</td>
                                        <td>@categoria.Descripcion</td>
                                        <td class="text-center">
                                            <a href="/Categoria/Modificar_Categoria?id=@categoria.Id_categoria" class="btn btn-primary" id="actualizar"><i class="fa fa-edit"></i></a>
                                            <button onclick="eliminar('@categoria.Id_categoria')" class="btn btn-danger" id="Eliminar"><i class="fa fa-trash"></i></button>

                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>




        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content">Desea eliminar la Categoria?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"> Eliminar</button><button class="btn btn-secondary" id="mod-can">Cancelar</button>
            </div>
        </div>

    </div>


</div>

<script>

    var f_id;

    document.addEventListener("DOMContentLoaded", function (e) {
        
        

        document.getElementById("mod-acept").addEventListener("click", function () {
            location.replace("/Categoria/eliminar?id=" + f_id);
            $("#mod").modal("hide");
        })
        document.getElementById("mod-can").addEventListener("click", function () {
            $("#mod").modal("hide");
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })

    function eliminar(id) {
        $("#mod").modal({ backdrop: true });
        f_id = id;
    }


</script>

Web_Farmacia/Views/Categoria/Modificar_Categoria.cshtml
@{
    ViewBag.Title = "Modificar_Categoria";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Modificar Categoria</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Modificar Categoria</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Modificar</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @model Web_Farmacia.Clases.Categoria



            <form method="post" enctype="multipart/form-data" id="modificar">
                <div class="d-flex">
                    <a href="@Url.Action("Consultar_Categoria", "Categoria")" class="btn btn-secondary ml-auto" @*id="return"*@><i class="fa fa-caret-left"></i> Regresar</a>
                </div>

                <div class="form-row">

                    <input class="form-control" type="hidden" name="id" id="id" value="@Model.Id_categoria">

                    <div class="form-group col-sm-6">
                        <label for="nombre">Nombre</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre" value="@Model.Nombre">
                        <span class="badge badge-warning sp" id="sp_nombre"></span>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="descripcion">Descripcion</label>
                        <input class="form-control" type="text" name="descripcion" id="descripcion" placeholder="Ingrese su Descripción" value="@Model.Descripcion">
                        <span class="badge badge-warning sp" id="sp_descripcion"></span>
                    </div>
                </div>
                
                
                    <div class="form-group col-auto">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                    
                


            </form>



        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->

<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"><i class="fa fa-caret-left"></i> Regresar</button>
            </div>
        </div>

    </div>


</div>

<script>
    document.addEventListener("DOMContentLoaded", function (e) {

        document.getElementById("modificar").addEventListener("submit", function (e) {

            var url = "@Url.Action("Modificar_Categoria", "Categoria")"/*"/Producto/Registrar_Producto"*/;

            //var form = document.getElementById("registrar");
            var id = document.getElementById("id").value;
            var nombre = document.getElementById("nombre").value;
            var descripcion = document.getElementById("descripcion").value;
            //var formdata = new FormData();

            var param = "id=" + id + "&nombre=" + nombre + "&descripcion=" + descripcion;
            var ajax = new XMLHttpRequest();

            ajax.onreadystatechange = function () {
                if (ajax.readyState == 4) {

                    //console.log(JSON.parse(ajax.responseText));

                    var response = JSON.parse(ajax.responseText);
                    if (response.success) {
                        console.log(response.message);

                        document.getElementById("content").innerHTML = response.message;
                        $("#mod").modal({ backdrop: true });
                        limpiar_spam();
                    } else {
                        console.log(response);
                        limpiar_spam();
                        for (var prop in response.datos) {
                            //console.log("propiedad " + prop + " valor " + response.datos[prop]);
                            document.getElementById(prop).innerHTML = response.datos[prop]
                        }
                    }
                }
            }

            ajax.open("POST", url, true);
            ajax.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            //console.log(formdata.toString);
            ajax.send(param);

            e.preventDefault();
        })

        document.getElementById("mod-acept").addEventListener("click", function () {
            $("#mod").modal("hide");

            location.replace("@Url.Action("Consultar_Categoria", "Categoria")");
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })


</script>

Web_Farmacia/Views/Categoria/Registrar_Categoria.cshtml
@{
    ViewBag.Title = "Registrar_Categoria";
    Layout = "~/Views/Main.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar Categoria</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Registrar Categoria</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Registrar</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            @if (ViewBag.message != null)
            {
                <div class="alert alert-dark" role="alert">
                    @ViewBag.message
                </div>
            }



            <form name="registrar" method="post" @*action="/Categoria/Registrar_Categoria"*@ enctype="multipart/form-data" id="registrar">

                <div class="d-flex">
                    <a href="@Url.Action("Consultar_Categoria", "Categoria")" class="btn btn-secondary ml-auto" @*id="return"*@><i class="fa fa-caret-left"></i> Lista de Categorias</a>
                </div>

                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="nombre">Nombre</label>
                        <input class="form-control" type="text" name="nombre" id="nombre" placeholder="Ingrese su Nombre">
                        <span class="badge badge-warning sp" id="sp_nombre"></span>
                    </div>
                    <div class="form-group col-sm-6">
                        <label for="descripcion">Descripcion</label>
                        <input class="form-control" type="text" name="descripcion" id="descripcion" placeholder="Ingrese su Descripción">
                        <span class="badge badge-warning sp" id="sp_descripcion"></span>
                    </div>
                </div>
                
                    <div class="form-group col-auto">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                  
            </form>



        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            Paginación
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
<div class="modal fade" id="mod" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Información</h4>
            </div>
            <div class="modal-body">
                <p id="content"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="mod-acept"> Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (e) {

        document.getElementById("registrar").addEventListener("submit", function (e) {

            var url = "@Url.Action("Registrar_Categoria", "Categoria")"/*"/Producto/Registrar_Producto"*/;

            //var form = document.getElementById("registrar");
            var nombre = document.getElementById("nombre").value;
            var descripcion = document.getElementById("descripcion").value;

            var formdata = new FormData();

            formdata.append("nombre", nombre);
            formdata.append("descripcion", descripcion);

            //var param = "nombre=" + nombre + "&descripcion=" + descripcion;
            var ajax = new XMLHttpRequest();

            ajax.onreadystatechange = function () {
                if (ajax.readyState == 4) {

                    //console.log(JSON.parse(ajax.responseText));

                    var response = JSON.parse(ajax.responseText);
                    if (response.success) {
                        console.log(response.message);
                        
                        document.getElementById("content").innerHTML = response.message;
                        $("#mod").modal({ backdrop: true });
                        limpiar_spam();
                    } else {
                        console.log(response);
                        limpiar_spam();
                        for (var prop in response.datos) {
                            //console.log("propiedad " + prop + " valor " + response.datos[prop]);
                            document.getElementById(prop).innerHTML = response.datos[prop]
                        }
                    }
                }
            }

            ajax.open("POST", url, true);
            //ajax.setRequestHeader("Content-Type", "multipart/byteranges");
            //console.log(formdata.toString);
            ajax.send(formdata/*param*/);

            e.preventDefault();
        })

        //--------------------------------------------

        document.getElementById("mod-acept").addEventListener("click", function () {
            $("#mod").modal("hide");

            document.getElementById("nombre").value = "";
            document.getElementById("descripcion").value = "";
            
        })

        function limpiar_spam() {
            var elementos = document.getElementsByClassName("sp");
            for (i = 0; i < elementos.length ; i++) {
                elementos.item(i).innerHTML = "";
            }
        }
    })




</script>